// src/client/components/District.tsx
import type { DistrictName, DistrictData } from "@/server/game/districts";
import { type CardSuit } from "@/server/game/types";
import { DistrictNameUtils } from "@/server/game/districts";

interface Props {
  name: DistrictName;
  beautified?: boolean;
  pos?: {
    x: number;
    y: number;
    z: number;
  };
  artifacts?: string[];
  enabled?: boolean;
  draggable?: boolean;
  height: number;
}
const aspectRatio = 3 / 4;

export function District(props: Props) {
  const data = DistrictNameUtils.data(props.name);
  const assetPath = `/public/districts/${String(data.id).padStart(2, "0")}.webp`;
  const { brightness, saturate } = districtLighting(props.name);
  return (
    <label
      data-dropzone=""
      className={`
        relative
        select-none
        cursor-pointer
        p-1 box-content
        rounded-2xl
        focus-visible:ring-4
        has-[:checked]:p-0
        has-[:checked]:border
        has-[:checked]:border-4
        has-[:checked]:border-green-500
        ${props.enabled ? "cursor-pointer" : ""}
        ${props.draggable ? "draggable" : ""}
      `}
      data-draggable={props.draggable ? "true" : undefined}
      style={{
        zIndex: props.pos?.z,
        transform: props.pos
          ? `translate(${props.pos.x}px, ${props.pos.y}px)`
          : undefined,
      }}
    >
      <div
        data-tip={data.description}
        className={`
          w-full
          rounded-t-xl relative h-10 bg-neutral-700
          ${data.description ? "tooltip tooltip-bottom tooltip-secondary before:w-full" : ""}
        `}
      >
        <div
          className={`
            absolute top-2
            leaded
            w-full text-center 
            font-serif
            text-base text-neutral-100
            ${props.name === "SchoolOfMagic" ? "ml-2" : ""}
            ${props.name === "ImperialTreasury" ? "ml-4" : ""}
            ${props.name === "HauntedQuarter" ? "ml-3" : ""}
          `}
        >
          {data.displayName}
        </div>
        <code
          className={`
            absolute top-2 left-2
            h-6 w-6 rounded-full
            leaded 
            flex flex-row justify-center items-center 
            text-black
            ${getSuitBgColor(data.suit)}
          `}
        >
          {data.cost}
        </code>
        {props.beautified && (
          <div
            data-tip="Beautified"
            className="
              absolute right-2 top-1 
              tooltip tooltip-secondary 
              text-2xl 
            "
          >
            ✨
          </div>
        )}
      </div>
      <svg
        className="rounded-b-xl"
        xmlns="http://www.w3.org/2000/svg"
        xmlnsXlink="http://www.w3.org/1999/xlink"
        height={props.height}
        style={{
          filter: `brightness(${brightness}) saturate(${props.enabled ? saturate : 0}`,
        }}
      >
        <image
          id="img"
          x={0}
          y={0}
          height="100%"
          xlinkHref={assetPath}
          preserveAspectRatio="xMinYMin slice"
        />
      </svg>
      <div className="absolute top-10" style={{ height: `${props.height}px` }}>
        <div className="flex flex-row flex-wrap gap-0 justify-center items-center h-full">
          {props.artifacts &&
            props.artifacts.map((item, index) => (
              <div
                key={index}
                className="rounded-full leaded h-10 w-10 draggable text-4xl bg-gradient-radial from-indigo-500 text-center"
              >
                {item}
              </div>
            ))}
        </div>
      </div>
    </label>
  );
}

// Helper function to determine suit background color
const getSuitBgColor = (suit: CardSuit): string => {
  switch (suit) {
    case "Noble":
      return "bg-yellow-300";
    case "Trade":
      return "bg-green-300";
    case "Military":
      return "bg-red-300";
    case "Religious":
      return "bg-blue-300";
    case "Unique":
      return "bg-purple-300";
    default:
      return "bg-gray-300";
  }
};

function districtCrop(name: DistrictName) {
  switch (name) {
    case "Manor":
      return { x: 0.236, y: 0.2 };
    case "Palace":
      return { x: 0.236, y: 0.05 };
    case "Temple":
      return { x: 0.236, y: 0.3 };
    case "Church":
      return { x: 0.236, y: 0.4 };
    case "Monastery":
      return { x: 0.236, y: 0.7 };
    case "Cathedral":
      return { x: 0.236, y: 0.7 };
    case "Market":
      return { x: 0.236, y: 0.7 };
    case "Tavern":
      return { x: 0.236, y: 0.4 };
    case "TradingPost":
      return { x: 0.236, y: 0.7 };
    case "Docks":
      return { x: 0.236, y: 0.5 };
    case "Harbor":
      return { x: 0.236, y: 0.7 };
    case "TownHall":
      return { x: 0.236, y: 0.6 };
    case "Prison":
      return { x: 0.236, y: 0.3 };
    case "Baracks":
      return { x: 0.236, y: 0.3 };
    case "Fortress":
      return { x: 0.236, y: 0.15 };
    case "Library":
      return { x: 0.27, y: 0.3 };
    case "GoldMine":
      return { x: 0.236, y: 0.3 };
    case "Statue":
      return { x: 0.236, y: 0.0 };
    case "SchoolOfMagic":
      return { x: 0.236, y: 0.3 };
    case "ImperialTreasury":
      return { x: 0.236, y: 0.3 };
    case "Observatory":
      return { x: 0.236, y: 0.12 };
    case "MapRoom":
      return { x: 0.236, y: 0.4 };
    case "DragonGate":
      return { x: 0.236, y: 0.4 };
    case "SecretVault":
      return { x: 0.236, y: 0.15 };
    case "Quarry":
      return { x: 0.236, y: 0.5 };
    case "HauntedQuarter":
      return { x: 0.236, y: 0.4 };
    case "GreatWall":
      return { x: 0.236, y: 0.2 };
    case "WishingWell":
      return { x: 0.236, y: 0.1 };
    case "Park":
      return { x: 0.25, y: 0.0 };
    case "Museum":
      return { x: 0.27, y: 0.1 };
    case "IvoryTower":
      return { x: 0.236, y: 0.05 };
    case "Laboratory":
      return { x: 0.236, y: 0.5 };
    case "Theater":
      return { x: 0.236, y: 0.2 };
    case "PoorHouse":
      return { x: 0.236, y: 0.5 };
    case "Smithy":
      return { x: 0.236, y: 0.2 };
    case "Framework":
      return { x: 0.236, y: 0.2 };
    case "ThievesDen":
      return { x: 0.236, y: 0.3 };
    case "Basilica":
      return { x: 0.236, y: 0.1 };
    case "Monument":
      return { x: 0.236, y: 0.1 };
    case "Factory":
      return { x: 0.236, y: 0.1 };
    case "Capitol":
      return { x: 0.236, y: 0.1 };
    default:
      return { x: 0.236, y: 0.0 };
  }
}

function districtLighting(name: DistrictName) {
  switch (name) {
    case "Manor":
      return { brightness: 1.3, saturate: 1.0 };
    case "Palace":
      return { brightness: 1.3, saturate: 1.0 };
    case "Temple":
      return { brightness: 1.3, saturate: 1.0 };
    case "Church":
      return { brightness: 1.3, saturate: 1.0 };
    case "Monastery":
      return { brightness: 1.3, saturate: 1.0 };
    case "Cathedral":
      return { brightness: 1.5, saturate: 1.0 };
    case "Market":
      return { brightness: 1.3, saturate: 1.0 };
    case "Tavern":
      return { brightness: 1.3, saturate: 1.0 };
    case "TradingPost":
      return { brightness: 1.3, saturate: 1.0 };
    case "Docks":
      return { brightness: 1.5, saturate: 1.0 };
    case "Harbor":
      return { brightness: 1.3, saturate: 1.0 };
    case "TownHall":
      return { brightness: 1.3, saturate: 1.0 };
    case "Prison":
      return { brightness: 1.5, saturate: 1.0 };
    case "Baracks":
      return { brightness: 1.3, saturate: 1.0 };
    case "Fortress":
      return { brightness: 1.5, saturate: 1.0 };
    case "Library":
      return { brightness: 1.0, saturate: 1.0 };
    case "GoldMine":
      return { brightness: 1.5, saturate: 1.0 };
    case "Statue":
      return { brightness: 1.3, saturate: 1.0 };
    case "SchoolOfMagic":
      return { brightness: 1.5, saturate: 1.0 };
    case "ImperialTreasury":
      return { brightness: 1.5, saturate: 1.0 };
    case "Observatory":
      return { brightness: 2.0, saturate: 1.0 };
    case "MapRoom":
      return { brightness: 1.5, saturate: 1.0 };
    case "DragonGate":
      return { brightness: 1.5, saturate: 1.0 };
    case "SecretVault":
      return { brightness: 1.3, saturate: 1.0 };
    case "Quarry":
      return { brightness: 1.3, saturate: 1.0 };
    case "HauntedQuarter":
      return { brightness: 1.3, saturate: 1.0 };
    case "GreatWall":
      return { brightness: 1.3, saturate: 1.0 };
    case "WishingWell":
      return { brightness: 2.0, saturate: 2.0 };
    case "Park":
      return { brightness: 1.2, saturate: 1.0 };
    case "Museum":
      return { brightness: 1.2, saturate: 1.0 };
    case "IvoryTower":
      return { brightness: 1.3, saturate: 1.0 };
    case "Laboratory":
      return { brightness: 1.3, saturate: 1.0 };
    case "Theater":
      return { brightness: 1.3, saturate: 1.0 };
    case "PoorHouse":
      return { brightness: 1.3, saturate: 1.0 };
    case "Smithy":
      return { brightness: 1.3, saturate: 1.0 };
    case "Framework":
      return { brightness: 1.3, saturate: 1.0 };
    case "ThievesDen":
      return { brightness: 1.3, saturate: 1.0 };
    case "Basilica":
      return { brightness: 1.3, saturate: 1.0 };
    case "Monument":
      return { brightness: 1.3, saturate: 1.0 };
    case "Factory":
      return { brightness: 1.3, saturate: 1.0 };
    case "Capitol":
      return { brightness: 1.3, saturate: 1.0 };
    default:
      return { brightness: 1.3, saturate: 1.0 };
  }
}

// angular/src/components/district/district.component.ts
import { Component, Input, input } from '@angular/core';
import { CommonModule } from '@angular/common';

import {
  DistrictName,
  DistrictData,
  DistrictNameUtils,
} from '@/core/districts';

@Component({
  selector: 'app-district',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './district.component.html',
})
export class DistrictComponent {
  @Input() name: string | null = null;
  @Input() selected: boolean = false;
  @Input() selectable: boolean = false;
  @Input() draggable: boolean = false;
  district?: District;

  ngOnChanges(): void {
    // eslint-disable-next-line
    this.district = DistrictFactory.fromDistrictName(this.name as DistrictName);
  }

  get labelStyle() {
    if (!this.district?.pos) return {};
    return {
      'z-index': this.district.pos.z,
      transform: `translate(${this.district.pos.x}px, ${this.district.pos.y}px)`,
    };
  }

  get districtNameMarginClass() {
    if (!this.district?.value) return {};
    return {
      'ml-2': this.district.value === 'SchoolOfMagic',
      'ml-4': this.district.value === 'ImperialTreasury',
      'ml-3': this.district.value === 'HauntedQuarter',
    };
  }

  getSuitBgColorClass(suit: CardSuit): string {
    switch (suit) {
      case 'Military':
        return 'bg-suit-military';
      case 'Religious':
        return 'bg-suit-religious';
      case 'Noble':
        return 'bg-suit-noble';
      case 'Trade':
        return 'bg-suit-trade';
      case 'Unique':
        return 'bg-suit-unique';
      default:
        return '';
    }
  }

  get svgFilterStyle() {
    if (!this.district?.asset) return {};
    return `brightness(${this.district.asset.brightness})`;
  }

  get artifactContainerStyle() {
    if (!this.district?.asset) return {};
    return {
      height: `${this.district.asset.height}px`,
    };
  }
}

export interface DistrictPosition {
  x: number;
  y: number;
  z: number;
}

export interface DistrictAsset {
  height: number | string;
  width: number | string;
  brightness: number;
  offset_x: number;
  offset_y: number;
  scale_percentage: number;
  path: string;
}

export type CardSuit = 'Military' | 'Religious' | 'Noble' | 'Trade' | 'Unique';

export interface District {
  value: string;
  name: string;
  description?: string | null;
  suit: CardSuit;
  cost?: number | null;
  beautified: boolean;
  pos: DistrictPosition;
  asset: DistrictAsset;
  artifacts: string[];
}

class DistrictFactory {
  public static fromDistrictName(
    districtName: DistrictName,
  ): District | undefined {
    const data: DistrictData = DistrictNameUtils.data(districtName);
    if (!data) return undefined;

    const length = 170.0;
    const scale = 10.0;
    const { x: p_x, y: p_y } = this.crop(districtName);
    // 'saturate' is calculated by lighting() but not part of TS DistrictAsset interface, so it's not used in 'asset'
    const { brightness /*, saturate */ } = this.lighting(districtName);

    const crop_offset_x = p_x * length;
    const crop_offset_y = p_y * length;

    const full_height = (length * scale) / 5.0;
    const full_width = length * (125.8 / 200.0) * (scale / 5.0);

    const asset: DistrictAsset = {
      brightness,
      path: '/public/districts.jpeg',
      height: length,
      width: length,
      scale_percentage: scale * 100.0,
      offset_x: -crop_offset_x - full_width * (data.id % 10),
      offset_y: -crop_offset_y - full_height * Math.floor(data.id / 10),
    };

    return {
      value: districtName,
      name: data.displayName,
      cost: districtName === 'SecretVault' ? null : data.cost,
      suit: data.suit,
      description: data.description ?? null,
      beautified: false, // Default value
      pos: { x: 0, y: 0, z: 0 }, // Default position
      artifacts: [], // Default empty artifacts
      asset,
    };
  }
  private static crop(districtName: DistrictName): { x: number; y: number } {
    switch (districtName) {
      // yellow
      case 'Manor':
        return { x: 0.236, y: 0.2 };
      case 'Palace':
        return { x: 0.236, y: 0.05 };

      // blue
      case 'Temple':
        return { x: 0.236, y: 0.3 };
      case 'Church':
        return { x: 0.236, y: 0.4 };
      case 'Monastery':
        return { x: 0.236, y: 0.7 };
      case 'Cathedral':
        return { x: 0.236, y: 0.7 };

      // green
      case 'Market':
        return { x: 0.236, y: 0.7 };
      case 'Tavern':
        return { x: 0.236, y: 0.4 };
      case 'TradingPost':
        return { x: 0.236, y: 0.7 };
      case 'Docks':
        return { x: 0.236, y: 0.5 };
      case 'Harbor':
        return { x: 0.236, y: 0.7 };
      case 'TownHall':
        return { x: 0.236, y: 0.6 };

      // red
      case 'Prison':
        return { x: 0.236, y: 0.3 };
      case 'Barracks':
        return { x: 0.236, y: 0.3 };
      case 'Fortress':
        return { x: 0.236, y: 0.15 };

      case 'Library':
        return { x: 0.27, y: 0.3 };
      case 'GoldMine':
        return { x: 0.236, y: 0.3 };
      case 'Statue':
        return { x: 0.236, y: 0.0 };
      case 'SchoolOfMagic':
        return { x: 0.236, y: 0.3 };
      case 'ImperialTreasury':
        return { x: 0.236, y: 0.3 };
      case 'Observatory':
        return { x: 0.236, y: 0.12 };
      case 'MapRoom':
        return { x: 0.236, y: 0.4 };
      case 'DragonGate':
        return { x: 0.236, y: 0.4 };
      case 'SecretVault':
        return { x: 0.236, y: 0.15 };
      case 'Quarry':
        return { x: 0.236, y: 0.5 };
      case 'HauntedQuarter':
        return { x: 0.236, y: 0.4 };
      case 'GreatWall':
        return { x: 0.236, y: 0.2 };
      case 'WishingWell':
        return { x: 0.236, y: 0.1 };
      case 'Park':
        return { x: 0.25, y: 0.0 };
      case 'Museum':
        return { x: 0.27, y: 0.1 };
      case 'IvoryTower':
        return { x: 0.236, y: 0.05 };
      case 'Laboratory':
        return { x: 0.236, y: 0.5 };
      case 'Theater':
        return { x: 0.236, y: 0.2 };
      case 'PoorHouse':
        return { x: 0.236, y: 0.5 };
      case 'Smithy':
        return { x: 0.236, y: 0.2 };
      case 'Framework':
        return { x: 0.236, y: 0.2 };
      case 'ThievesDen':
        return { x: 0.236, y: 0.3 };
      case 'Basilica':
        return { x: 0.236, y: 0.1 };
      case 'Monument':
        return { x: 0.236, y: 0.1 };
      case 'Factory':
        return { x: 0.236, y: 0.1 };
      case 'Capitol':
        return { x: 0.236, y: 0.1 };
      default:
        return { x: 0.236, y: 0.0 };
    }
  }

  private static lighting(districtName: DistrictName): {
    brightness: number;
    saturate: number;
  } {
    switch (districtName) {
      // yellow
      case 'Manor':
        return { brightness: 1.3, saturate: 1.0 };
      case 'Palace':
        return { brightness: 1.3, saturate: 1.0 };

      // blue
      case 'Temple':
        return { brightness: 1.3, saturate: 1.0 };
      case 'Church':
        return { brightness: 1.3, saturate: 1.0 };
      case 'Monastery':
        return { brightness: 1.3, saturate: 1.0 };
      case 'Cathedral':
        return { brightness: 1.5, saturate: 1.0 };

      // green
      case 'Market':
        return { brightness: 1.3, saturate: 1.0 };
      case 'Tavern':
        return { brightness: 1.3, saturate: 1.0 };
      case 'TradingPost':
        return { brightness: 1.3, saturate: 1.0 };
      case 'Docks':
        return { brightness: 1.5, saturate: 1.0 };
      case 'Harbor':
        return { brightness: 1.3, saturate: 1.0 };
      case 'TownHall':
        return { brightness: 1.3, saturate: 1.0 };

      // red
      case 'Prison':
        return { brightness: 1.5, saturate: 1.0 };
      case 'Barracks':
        return { brightness: 1.3, saturate: 1.0 };
      case 'Fortress':
        return { brightness: 1.5, saturate: 1.0 };

      case 'Library':
        return { brightness: 1.0, saturate: 1.0 };
      case 'GoldMine':
        return { brightness: 1.5, saturate: 1.0 };
      case 'Statue':
        return { brightness: 1.3, saturate: 1.0 };
      case 'SchoolOfMagic':
        return { brightness: 1.5, saturate: 1.0 };
      case 'ImperialTreasury':
        return { brightness: 1.5, saturate: 1.0 };
      case 'Observatory':
        return { brightness: 2.0, saturate: 1.0 };
      case 'MapRoom':
        return { brightness: 1.5, saturate: 1.0 };
      case 'DragonGate':
        return { brightness: 1.5, saturate: 1.0 };
      case 'SecretVault':
        return { brightness: 1.3, saturate: 1.0 };
      case 'Quarry':
        return { brightness: 1.3, saturate: 1.0 };
      case 'HauntedQuarter':
        return { brightness: 1.3, saturate: 1.0 };
      case 'GreatWall':
        return { brightness: 1.3, saturate: 1.0 };
      case 'WishingWell':
        return { brightness: 2.0, saturate: 2.0 };
      case 'Park':
        return { brightness: 1.2, saturate: 1.0 };
      case 'Museum':
        return { brightness: 1.2, saturate: 1.0 };
      case 'IvoryTower':
        return { brightness: 1.3, saturate: 1.0 };
      case 'Laboratory':
        return { brightness: 1.3, saturate: 1.0 };
      case 'Theater':
        return { brightness: 1.3, saturate: 1.0 };
      case 'PoorHouse':
        return { brightness: 1.3, saturate: 1.0 };
      case 'Smithy':
        return { brightness: 1.3, saturate: 1.0 };
      case 'Framework':
        return { brightness: 1.3, saturate: 1.0 };
      case 'ThievesDen':
        return { brightness: 1.3, saturate: 1.0 };
      case 'Basilica':
        return { brightness: 1.3, saturate: 1.0 };
      case 'Monument':
        return { brightness: 1.3, saturate: 1.0 };
      case 'Factory':
        return { brightness: 1.3, saturate: 1.0 };
      case 'Capitol':
        return { brightness: 1.3, saturate: 1.0 };
      default:
        return { brightness: 1.3, saturate: 1.0 };
    }
  }
}

<div class="flex flex-row" *ngIf="district">
  <label
    data-dropzone
    [attr.data-district]="district.value"
    [id]="'card-' + district.value"
    class="
      relative
      select-none
      p-1 box-content
      rounded-2xl
      has-[:focus-visible]:ring-4
      has-[:checked]:p-0
      has-[:checked]:border
      has-[:checked]:border-4
      has-[:checked]:border-success
    "
    [class.cursor-pointer]="selectable || draggable"
    [class.draggable]="draggable"
    [attr.data-draggable]="draggable ? '' : null"
    [attr.data-x]="district.pos.x + 'px'"
    [attr.data-y]="district.pos.y + 'px'"
    [ngStyle]="labelStyle"
  >
    <div
      [attr.data-tip]="district.description"
      class="w-full rounded-t-xl relative h-10 bg-slate-800"
      [ngClass]="{
        'tooltip': district.description,
        'tooltip-bottom': district.description,
        'tooltip-secondary': district.description,
        'before:w-full': district.description
      }"
    >
      <div
        class="
          absolute top-2
          leaded
          w-full text-center
          font-serif
          text-base text-neutral-content
        "
        [ngClass]="districtNameMarginClass"
      >
        {{ district.name }}
      </div>
      <code
        class="
          absolute top-2 left-2
          h-6 w-6 rounded-full
          leaded
          flex flex-row justify-center items-center
          text-black
        "
        [ngClass]="getSuitBgColorClass(district.suit)"
      >
        @if ( district.cost != null) {
          {{ district.cost }}
        }
      </code>
      <div
        *ngIf="district.beautified"
        data-tip="Beautified"
        class="
          absolute right-2 top-1
          tooltip tooltip-secondary
          text-2xl
        "
      >
        ✨
      </div>
    </div>
    <input
      type="checkbox"
      class="absolute top-0 peer opacity-0"
      name="district"
      [value]="district.value"
      [disabled]="!selectable"
      [checked]="selected"
    />
    <ng-container *ngIf="district.asset as asset">
      <svg
        class="rounded-b-xl"
        xmlns="http://www.w3.org/2000/svg"
        xmlns:xlink="http://www.w3.org/1999/xlink"
        [attr.height]="asset.height"
        [attr.width]="asset.width"
        [style.filter]="svgFilterStyle"
      >
        <image
          id="img"
          [attr.x]="asset.offset_x"
          [attr.y]="asset.offset_y"
          [attr.height]="asset.scale_percentage + '%'"
          [attr.xlink:href]="asset.path"
          preserveAspectRatio="xMinYMin slice"
        />
      </svg>
      <div
        class="absolute top-10"
        [ngStyle]="artifactContainerStyle"
      >
        <div class="flex flex-row flex-wrap gap-0 justify-center items-center h-full">
          <div
            *ngFor="let item of district.artifacts"
            class="rounded-full leaded h-10 w-10 draggable text-4xl bg-gradient-radial from-indigo-500 text-center"
          >
            {{ item }}
          </div>
        </div>
      </div>
    </ng-container>
  </label>
</div>
