// angular/src/components/district/district.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'district',
  imports: [],
  templateUrl: './district.component.html'
})
export class DistrictComponent {

}

<!-- Check if district is loaded to prevent errors during initialization -->
<ng-container *ngIf="district">
  <label
    data-dropzone
    [attr.data-district]="district.value"
    [id]="'card-' + district.value"
    class="
      relative
      select-none
      p-1 box-content
      rounded-2xl
      has-[:focus-visible]:ring-4
      has-[:checked]:p-0
      has-[:checked]:border
      has-[:checked]:border-4
      has-[:checked]:border-success
    "
    [class.cursor-pointer]="enabled"
    [class.draggable]="draggable"
    [attr.data-draggable]="draggable ? '' : null"
    [attr.data-x]="district.pos.x + 'px'"
    [attr.data-y]="district.pos.y + 'px'"
    [ngStyle]="labelStyle"
  >
    <div
      [attr.data-tip]="district.description"
      class="w-full rounded-t-xl relative h-10 bg-neutral"
      [ngClass]="{
        'tooltip': district.description,
        'tooltip-bottom': district.description,
        'tooltip-secondary': district.description,
        'before:w-full': district.description
      }"
    >
      <div
        class="
          absolute top-2
          leaded
          w-full text-center
          font-serif
          text-base text-neutral-content
        "
        [ngClass]="districtNameMarginClass"
      >
        {{ district.name }}
      </div>
      <code
        class="
          absolute top-2 left-2
          h-6 w-6 rounded-full
          leaded
          flex flex-row justify-center items-center
          text-black
        "
        [ngClass]="getSuitBgColorClass(district.suit)"
      >
        <ng-container *ngIf="district.cost !== null && district.cost !== undefined">
          {{ district.cost }}
        </ng-container>
      </code>
      <div
        *ngIf="district.beautified"
        data-tip="Beautified"
        class="
          absolute right-2 top-1
          tooltip tooltip-secondary
          text-2xl
        "
      >
        ✨
      </div>
    </div>
    <input
      [type]="inputType"
      class="absolute top-0 peer opacity-0"
      name="district"
      [value]="district.value"
      [disabled]="!enabled"
      (keyup.enter)="onInputKeyupEnter($event)"
    />
    <ng-container *ngIf="district.asset as asset">
      <svg
        class="rounded-b-xl"
        xmlns="http://www.w3.org/2000/svg"
        xmlns:xlink="http://www.w3.org/1999/xlink"
        [attr.height]="asset.height"
        [attr.width]="asset.width"
        [style.filter]="svgFilterStyle"
      >
        <image
          id="img"
          [attr.x]="asset.offset_x"
          [attr.y]="asset.offset_y"
          [attr.height]="asset.scale_percentage + '%'"
          [attr.xlink:href]="asset.path"
          preserveAspectRatio="xMinYMin slice"
        />
      </svg>
      <div
        class="absolute top-10"
        [ngStyle]="artifactContainerStyle"
      >
        <div class="flex flex-row flex-wrap gap-0 justify-center items-center h-full">
          <div
            *ngFor="let item of district.artifacts"
            class="rounded-full leaded h-10 w-10 draggable text-4xl bg-gradient-radial from-indigo-500 text-center"
          >
            {{ item }}
          </div>
        </div>
      </div>
    </ng-container>
  </label>
</ng-container>

// src/components/District.tsx
import React from "react";
import { DistrictName } from "../game/districts";
import { CardSuit } from "../game/types";

interface DistrictAsset {
  height: number;
  width: number;
  brightness: number;
  offset_x: number;
  offset_y: number;
  scale_percentage: number;
  path: string;
}

interface DistrictProps {
  district: {
    value: DistrictName;
    name: string;
    description?: string;
    suit: CardSuit;
    cost?: number;
    beautified?: boolean;
    pos: {
      x: number;
      y: number;
      z: number;
    };
    asset: DistrictAsset;
    artifacts: string[];
  };
  inputType?: "radio" | "checkbox";
  draggable?: boolean;
  enabled?: boolean;
}

const District: React.FC<DistrictProps> = ({
  district,
  inputType = "radio",
  draggable = true,
  enabled = true,
}) => {
  // Helper function to determine suit background color
  const getSuitBgColor = (suit: CardSuit): string => {
    switch (suit) {
      case "Noble":
        return "bg-yellow-300";
      case "Trade":
        return "bg-green-300";
      case "Military":
        return "bg-red-300";
      case "Religious":
        return "bg-blue-300";
      case "Unique":
        return "bg-purple-300";
      default:
        return "bg-gray-300";
    }
  };

  return (
    <label
      data-dropzone=""
      data-district={district.value}
      id={`card-${district.value}`}
      className={`
        relative
        select-none
        cursor-pointer
        p-1 box-content
        rounded-2xl
        focus-visible:ring-4
        has-[:checked]:p-0
        has-[:checked]:border
        has-[:checked]:border-4
        has-[:checked]:border-green-500
        ${enabled ? "cursor-pointer" : ""}
        ${draggable ? "draggable" : ""}
      `}
      data-draggable={draggable ? "true" : undefined}
      data-x={`${district.pos.x}px`}
      data-y={`${district.pos.y}px`}
      style={{
        zIndex: district.pos.z,
        transform: `translate(${district.pos.x}px, ${district.pos.y}px)`,
      }}
    >
      <div
        data-tip={district.description}
        className={`
          w-full
          rounded-t-xl relative h-10 bg-neutral-700
          ${district.description ? "tooltip tooltip-bottom tooltip-secondary before:w-full" : ""}
        `}
      >
        <div
          className={`
            absolute top-2
            leaded
            w-full text-center 
            font-serif
            text-base text-neutral-100
            ${district.value === "SchoolOfMagic" ? "ml-2" : ""}
            ${district.value === "ImperialTreasury" ? "ml-4" : ""}
            ${district.value === "HauntedQuarter" ? "ml-3" : ""}
          `}
        >
          {district.name}
        </div>
        <code
          className={`
            absolute top-2 left-2
            h-6 w-6 rounded-full
            leaded 
            flex flex-row justify-center items-center 
            text-black
            ${getSuitBgColor(district.suit)}
          `}
        >
          {district.cost}
        </code>
        {district.beautified && (
          <div
            data-tip="Beautified"
            className="
              absolute right-2 top-1 
              tooltip tooltip-secondary 
              text-2xl 
            "
          >
            ✨
          </div>
        )}
      </div>
      <input
        type={inputType}
        className="absolute top-0 peer opacity-0"
        name="district"
        value={district.value}
        disabled={!enabled}
        onKeyUp={(e) => {
          if (e.key === "Enter") {
            const target = e.target as HTMLInputElement;
            target.checked = !target.checked;
            target.dispatchEvent(new Event("change", { bubbles: true }));
          }
        }}
      />
      <svg
        className="rounded-b-xl"
        xmlns="http://www.w3.org/2000/svg"
        xmlnsXlink="http://www.w3.org/1999/xlink"
        height={district.asset.height}
        width={district.asset.width}
        style={{ filter: `brightness(${district.asset.brightness})` }}
      >
        <image
          id="img"
          x={district.asset.offset_x}
          y={district.asset.offset_y}
          height={`${district.asset.scale_percentage}%`}
          xlinkHref={district.asset.path}
          preserveAspectRatio="xMinYMin slice"
        />
      </svg>
      <div
        className="absolute top-10"
        style={{ height: `${district.asset.height}px` }}
      >
        <div className="flex flex-row flex-wrap gap-0 justify-center items-center h-full">
          {district.artifacts.map((item, index) => (
            <div
              key={index}
              className="rounded-full leaded h-10 w-10 draggable text-4xl bg-gradient-radial from-indigo-500 text-center"
            >
              {item}
            </div>
          ))}
        </div>
      </div>
    </label>
  );
};

export default District;
